# Structure of the course {#structure}

Check which questions we cover per session. One session is meant to consist of maximal 1 hour lecture (depending on the topic also less) as well as a homework that takes about 1.5 hours to complete.

**Session 1: Before you learn the language** 

- Why learning R
- How to use R as a beginner
- Types of R files
- Ensuring reproducibility
- How to learn the language

 


**Session 2: Introduction to R**  

- working directory demonstration
- objects in R
- functions and their arguments
- data types
  - atomic vectors 
  - lists 
  - dataframes/tibbles 
- subsetting vectors


**Session 3: Import data and how to work with dataframes**  

- what are dataframes 
- how to create dataframes 
- basic properties of dataframes 
- how to import and export data 
- Selecting and filtering your data 
- the pipe operator %>%


**Session 4: Data transformation, data summary, functions and conditional execution**   

- mutate 
- summarise 
- group_by 
- write your own functions 
- use if/else statements



**Session 5: ggplot2 basics and Iteration**   

- grammar of graphics
- scatterplot with regression line 
- for loops 
- while loops 
- map function 



**Session 6: ggplot2**   

- scatterplots 
- linegraphs 
- boxplots 
- histograms 
- barplots 


**Session 7: Basics of Linear Regression**  

- how linear regression utilizes the gaussian distribution  
- which assumptions does this imply?  
- how to perform basic multiple linear regression in R  
- how to test these assumptions   


**Session 8: Using Rmarkdown for scientific reporting**  