






# Homeworks 




**Session 1: Before you learn the language** 

Create an rProject using Rstudio incl. a folder for your R code and your data.




**Session 2: Introduction to R**  

1. Read the intro of the [Tidyverse coding style guide](https://style.tidyverse.org/files.html). Read on during the course whenever in doubt what the correct style is.
2. Download the [script](https://raw.githubusercontent.com/HenrikEckermann/donders_r/master/course_project/R/basics.R) and try to understand the content.
3. Then, create 3 vectors: A logical, a character and a numeric one that have an equal length of 5.
4. Create a list that contains all the vectors.
5. Take one of the vectors and select:
   - the last element
   - all except the first element
6. Then take the list and select:
   - the first element as a list 
   - the second element of the third element in the list.





**Session 3: Working with dataframes**  

1. Go through the [script](https://github.com/HenrikEckermann/donders_r/raw/master/course_project/R/dataframes_and_import_data.R), read the comments and understand the code.
2. Create a new R file in your project and import your own data in R as a dataframe. 
3. How many rows and columns does your dataframe have?
4. What are the datatypes of the vectors within your dataframe?
5. Create another new R file called dataframes.R. Open it. In R, there is a preloaded dataframe called "mtcars". Using only the methods we learned today, try to perform the following actions:
   - Take a look at the first 10 rows and last 10 rows
   - Create a new dataframe that only retains the columns mpg, disp and hp of cars that have 6 cylinders (cyl is the column for the number of cylinders). First use the base R method using the brackets. Then use dplyr functions to achieve the same!
   - if you did not already: answer the same question but use the %>% operator to get to your answer!
   - How many observations are in this new dataframe?
   - export that dataframe to an excel file in your data folder


**Session 4: Data manipulation, functions and conditional execution**  
1. Download the [script](https://github.com/HenrikEckermann/donders_r/blob/master/course_project/R/datamanipulation_and_functions.R) and try to understand the content.  
2. Structure and manipulate your own data as far as you can. Also obtain useful summary statistics of your own data by making use of group_by and summarise functions.  
3. Write a function that takes as arguments two numeric vectors and returns a named list that shows the Pearson as well as the Spearman correlation of these vectors.  
4. Now rewrite this function by giving it another argument (linear = FALSE). Write the function so that it returns Pearson correlation when linear == TRUE and otherwise Spearman correlation.
