--- 
title: "DondeRs Group"
author: "Henrik Eckermann"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This bookdown-project contains introductory material to learn the R programming language"
---

# Overview

This minmal website contains information about the R course-sessions we will organize such as:  

- links to books and introductory material
- homeworks (followed by solutions) 

It will be updated regularly and I will point to updates in the course lectures! 

**Instructor:**  
My name is Henrik. I am a PhD-candidate in the Developmental Psychobiology lab group at the Donders Institute in Nijmegen. I find that the R programming language is an extremely useful tool for Scientists, especially (but not only) for data analysis and visualization. I can help you learning the basics of the R programming language and how to approach learning a programming language so you can advance in learning whatever is needed in your specific field. 


**Target audience:**  
Anyone at Donders Institute who would like to get started with the R programming language.  

**Learning goals:**  
Students will become familiar with the basics of the R programming language and the [tidyverse style](https://style.tidyverse.org/) of R programming. The goal is that students will feel empowered to acquire any R skill that they need for their specific work.

**How to make optimal use of this course:**  
Researchers are often highly variable in their understanding and knowledge of a particular programming language independent of their degree. To avoid wasting your time, check if the topic of a particular R meeting is useful for you. This course is meant for beginners who need guidance and who prefer learning a programming language in a group rather than by themselves. 



## Preparing for the course


### Software setup


Follow the below steps before the course:

1. Install/Update R: [Download](https://cran.r-project.org) and install the newest R version. 
2. Install/Update Rstudio: [Click here](https://www.rstudio.com/products/rstudio/download/) and choose "Rstudio Desktop" (Open Source License) to download the newest version of Rstudio. 


### Ressources

1. [Tidyverse coding style](https://style.tidyverse.org/index.html)

2. [Data Analysis and Visualization in R for Ecologists](https://datacarpentry.org/R-ecology-lesson/) by Data Carpentry 
3. [Statistical Inference via Data Science - A ModernDive into R and the tidyverse](https://moderndive.com/index.html)
4. [R for Datascience](https://r4ds.had.co.nz/)



## Contact  
Contact me via [email](mailto:henrikeckermann87@gmail.com) for questions or feedback.




